version: '3.1'

services:

  db:
    image: mysql:5.7.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123!@#

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
